### PR TITLE
Upload Reformatted Code Base

### PR DESCRIPTION
**Pull request by Briancbn**
First of all, congradulate @dejaniraai on the new job!! :) 

As @dejaniraai is not continuing working on this, I will be in charge of maintaining this package from the ROS-I AP side.

The code base is mostly the same as #1 with the following changes added:
* Use **industrial_ci** for the Travis CI Pipeline (A clean-up on the travis-ci commits as well)
* Reformat code using the default **ament_auto_lint** checks (style guide following that of **uncrustify**. Let me know if other tools like **clang_tidy** are preferred here)
* Clean up `README.md` setup and usage instructions
* Fix `rosdep` as pointed out by @gavanderhoorn in #1 
* Add timeout for `packml_plugin` waiting for status and some utest checks
* Resolve the comments given by @Levi-Armstrong  #1 

Dear maintainers, I think this is now ready for review:) !

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
So this PR is a little too big to review properly.

Two high-level comments: should the Gitlab CI configuration be kept here? And I'd suggest migrating this repository to use Github Actions. That would make the Travis `.yml` redundant as well.

Other than that: if you've addressed the comments from last time, we can probably merge.

I don't have a way to test this, but we should not let this PR sit too long / any longer.

**Comment by gavanderhoorn** [comment]
I'm not suggesting to migrate to GHA in this PR btw. Just noting the potential unneeded CI configs.

**Comment by Briancbn** [comment]
> Two high-level comments: should the Gitlab CI configuration be kept here? And I'd suggest migrating this repository to use Github Actions. That would make the Travis `.yml` redundant as well.

Hi @gavanderhoorn, I will migrate some of the work done in [this fork](https://github.com/1487quantum/packml_ros2/tree/master), GHA should be good to go after that. I will take note to remove the redundant configurations.

**Comment by Briancbn** [comment]
@gavanderhoorn @cardboardcode Action passes for [my fork](https://github.com/Briancbn/packml_ros2/actions/runs/1286687369). I believe the GHA and codecov might need activation for this repository to run CI build.

**Comment by gavanderhoorn** [comment]
At least for GHA everything is already active.

You cannot 'activate' GHA in a PR afaik. It will only start working *after* your PR is merged

**Review by gavanderhoorn — APPROVED** [review]
Approved with the caveats mentioned in my earlier comments.

**Comment by gavanderhoorn** [comment]
I'll leave merging to you @Briancbn or @cardboardcode.

**Pull request merged**
